//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntColonyEntityContainer : DbContext
    {
        public AntColonyEntityContainer()
            : base("name=AntColonyEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<RootAdmin> RootAdmin { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Team_Relation_User> Team_Relation_User { get; set; }
        public virtual DbSet<TeamTypeTable> TeamTypeTable { get; set; }
        public virtual DbSet<Power> Power { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<Role_Post_Power> Role_Post_Power { get; set; }
        public virtual DbSet<Role_Post_User> Role_Post_User { get; set; }
        public virtual DbSet<SpecialPermissionTable> SpecialPermissionTable { get; set; }
        public virtual DbSet<TeamRoleTable> TeamRoleTable { get; set; }
        public virtual DbSet<TeamRole_Post_Power> TeamRole_Post_Power { get; set; }
        public virtual DbSet<TeamSpecialPermissionTable> TeamSpecialPermissionTableSet { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectMessage> ProjectMessage { get; set; }
        public virtual DbSet<ProjectType> ProjectType { get; set; }
        public virtual DbSet<ProjectFile> ProjectFile { get; set; }
        public virtual DbSet<ProjectFileTag> ProjectFileTag { get; set; }
        public virtual DbSet<ProjectTaskList> ProjectTaskList { get; set; }
        public virtual DbSet<ProjectStateTable> ProjectStateTable { get; set; }
    }
}
