//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Team = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyInfo { get; set; }
        public string CompanyIcon { get; set; }
        public string CompanyUrl { get; set; }
        public string CompanyAddress { get; set; }
        public string CorporaterepResentative { get; set; }
        public int CompanyMainUser { get; set; }
        public string CompanyTerritory { get; set; }
        public System.DateTime CompanyYearOfEstablishment { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public short State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Team { get; set; }
    }
}
