//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string RealyName { get; set; }
        public string Pwd { get; set; }
        public bool Sex { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public bool State { get; set; }
        public string Image { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectTaskList ProjectTaskList { get; set; }
    }
}
